version: "3.8"

services:
  minelink:
    container_name: minelink
    image: minelink:latest
    build: .
    restart: unless-stopped
    volumes:
      - ./config:/app/config
    ports:
      - "19132:19132/udp"
      - "19132:19132/tcp"